# Generated by Django 2.2.13 on 2021-01-30 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0013_auto_20210124_1953'),
        ('teachers', '0002_auto_20201224_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.CharField(max_length=255)),
                ('place_class_taken', models.CharField(max_length=255)),
                ('class_duration', models.CharField(max_length=255)),
                ('attend_student', models.IntegerField(default=0)),
                ('total_class_remain_student', models.IntegerField(default=0)),
                ('average', models.CharField(max_length=10)),
                ('is_assignment', models.CharField(max_length=5)),
                ('is_quiz', models.CharField(max_length=5)),
                ('phone_call_quantity', models.IntegerField(default=0)),
                ('class_video_link', models.URLField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Semester')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.Teacher')),
            ],
        ),
    ]
